### ISSUE TITLE
Single quoted double quote breaks highlight

### ISSUE THREAD

**Issue by TWiStErRob** [nishtahir/language-kotlin#10]
Originally reported at https://github.com/github/linguist/issues/4361

`'"'` seems to start a new String literal, instead of being recognized as a character literal. See how most of the code is blue: https://github.com/holgerbrandl/kscript/blob/c9f515ed3bb7855dd325b35672311e803aa9312a/src/main/kotlin/kscript/app/Script.kt#L166

![image](https://user-images.githubusercontent.com/2906988/50450731-a51c9880-0927-11e9-99eb-91cf7cad583c.png)

**Comment by nishtahir** [comment]
Should be resolved in the next linguist deployment.

**Comment by TWiStErRob** [comment]
Nice, thanks!
