### ISSUE TITLE
Single line comments break formatting

### ISSUE THREAD

**Issue by CreamyCookie** [nishtahir/language-kotlin#14]
Example from: https://github.com/junkdog/bitvector/blob/master/core/src/main/kotlin/net/onedaybeard/bitvector/BitVector.kt#L28

![screenshot](https://user-images.githubusercontent.com/3063858/61797544-e32f5b80-ae27-11e9-9d29-cdb00d26ec5e.png)

**Comment by nishtahir** [comment]
I just tested this against 61a70d4 on Lightshow. Looks like this was somewhat related to #15. This should
