### ISSUE TITLE
Having ? before method calls breaks highlighting 

### ISSUE THREAD

**Issue by seratch** [nishtahir/language-kotlin#17]
https://gist.github.com/seratch/8b02c69215a4295aeb4700f99cc3ab3f

```kotlin
foo(barBaz?.doSomething())
```

```kotlin
foo(barBaz.doSomething())
```

<img width="313" alt="Screen Shot 2019-11-23 at 23 12 14" src="https://user-images.githubusercontent.com/19658/69479969-bc6d4a00-0e46-11ea-8f19-43734b83d2c3.png">

**Comment by nishtahir** [comment]
This should be fixed here https://github.com/nishtahir/language-kotlin/commit/9634d7df2d0f4aa4656df8d6f3745726ba9d1758
