### ISSUE TITLE
Kotlin syntax highlighting on github no longer working

### ISSUE THREAD

**Issue by patkujawa-wf** [nishtahir/language-kotlin#33]
Per linguist, I figured I'd post here to see if anyone else is seeing Kotlin highlighting no longer working on github. I know it was, at a certain point, for our particular repo and files, but now it isn't :( 

> If you experience an issue with the syntax-highlighting on GitHub, please report the issue to the upstream grammar repository, not here. Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.

**Comment by nishtahir** [comment]
Thanks for reporting this. I'm looking into it. [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fnishtahir%2Flanguage-kotlin%2Fmaster%2Fdist%2FKotlin.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=class+Kotlin+%7B%0D%0A%0D%0A+fun+test%28%29+%7B%0D%0A%0D%0A+%7D%0D%0A%7D) seems to be rendering it correctly if I use the raw URL of the grammar. However, it doesn't seem to render if I use the scope directly

**Comment by nishtahir** [comment]
Looks like this may have been the result of a recent linguist deployment https://github.com/github/linguist/pull/5084

**Comment by lildude** [comment]
Syntax highlighting is working again. Sorry for the inconvenience.

**Comment by patkujawa-wf** [comment]
Thank you both!
