### ISSUE TITLE
!is highlighted as keyword when part of a negated variable name

### ISSUE THREAD

**Issue by TWiStErRob** [nishtahir/language-kotlin#44]
```kotlin
a = b !is C // type check keyword, all good
a = b ! is C // type check keyword, all good
a.b = !isC // variable name, no-no
a.b = ! isC // split operator fixes it, but I haven't seen this style anywhere
```
Notice how in `!isC` `!is` is highlighted as a keyword.

**Comment by TWiStErRob** [comment]
Nice, thanks for the quick fix. How often does GitHub pull and build this?

**Comment by nishtahir** [comment]
That is upto the [Linguist](https://github.com/github/linguist/) team. Releases usually happen monthly as far as I can tell.
There is a release happening [soon](https://github.com/github/linguist/pull/5209)
