### ISSUE TITLE
Syntax Highlighting Issue

### ISSUE THREAD

**Issue by gantonious** [nishtahir/language-kotlin#5]
I haven't had enough time to look into the exact issue but I noticed earlier today that Kotlin syntax highlighting isn't working as expected. See the following sample file in linguist: https://github.com/github/linguist/blob/master/samples/Kotlin/Foo.kt

It looks like linguist just had a release earlier today and I think that's when it broke. See https://github.com/github/linguist/pull/4324.

**Comment by Grohden** [comment]
It's happening here too

https://github.com/levibostian/Wendy-Android/blob/b93f22b7da53250cb1e78bbbe09129378af0109e/wendy/src/main/java/com/levibostian/wendy/WendyConfig.kt#L89

**Comment by gantonious** [comment]
Just a quick follow up from yesterday. I quickly spun up a VSCode language extension using the same syntax currently being used by linguist and it seems to be working fine in VSCode:

![image](https://user-images.githubusercontent.com/9062713/48481308-0f93d200-e7db-11e8-9039-d77c33ef50bb.png)

**Comment by nishtahir** [comment]
Thanks for reporting this. I started looking into this yesterday and it seems that the bug has something to do with https://github.com/nishtahir/language-kotlin/blob/7631a679e35ba0cd55aadd27ce850f5874894607/syntax/Kotlin.tmLanguage#L809 which was to allow for generics in types.

It looks like VSCode and GitHub treat these very differently. After removing it and testing it with lightshow. It seems to work correctly.

I'll be making a patch to fix it shortly

**Comment by Zhuinden** [comment]
Is this fix out and available? I'm asking because PRs that I'm reviewing still show up with pretty much all the code ending up in a blue-ish tint.

**Comment by gantonious** [comment]
It should be out when [github/lingust](https://github.com/github/linguist) does another release. See: https://github.com/github/linguist/issues/4329

**Comment by lildude** [comment]
GitHub should now be rendering Kotlin files correctly again.

**Comment by nishtahir** [comment]
Thanks, @lildude!
