### ISSUE TITLE
data is highlighted as a class modifier in different scenarios

### ISSUE THREAD

**Issue by starsep** [nishtahir/language-kotlin#50]
It seems that `data` is always highlighted as a class modifier i.e. as in `data class`.

```kotlin
fun foo(data: String) {}
val data = "42"
foo(data = data)

data class Klass(val data: Int)
Klass(data = 42)
```

**Comment by Animeshz** [comment]
Same goes for keywords like
```kotlin
val expect: String
val actual: Int
val vararg: List<Int>
```

We can add a negative lookahead on the soft keywords to fix this.
https://github.com/nishtahir/language-kotlin/blob/5738095b675a42b520b40b673ba2ea52f50cd91c/src/keywords.YAML-tmLanguage#L23
