### ISSUE TITLE
Content after triple quotes highlighted as string

### ISSUE THREAD

**Issue by starsep** [nishtahir/language-kotlin#53]
Another issue similar to #26
From highlighting it seems that content of a string after newline is interpreted as a Kotlin code.

```kotlin
    private fun lastChecked(yearsAgo: Double): String = """
        older today -$yearsAgo years
        or ${LAST_CHECK_DATE_KEYS.joinToString(" or ") { "$it < today -$yearsAgo years" }}
    """.trimIndent()
    private fun hasAnyName(tags: Map<String, String>?): Boolean =
        tags?.let { featureDictionaryFuture.get().byTags(it).find().isNotEmpty() } ?: false
```
Source: https://github.com/streetcomplete/StreetComplete/blob/07137c1f506530dc86a500faa4ee04bda91215e5/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt#L101-L107

**Comment by Animeshz** [comment]
Interesting enough it only happens if the string is returned from a function 👀 

```kotlin
   val str: String = """
        older today -$yearsAgo years
        or ${LAST_CHECK_DATE_KEYS.joinToString(" or ") { "$it < today -$yearsAgo years" }}
    """.trimIndent()
    private fun hasAnyName(tags: Map<String, String>?): Boolean =
        tags?.let { featureDictionaryFuture.get().byTags(it).find().isNotEmpty() } ?: false
```

Assignment or any other type of literals are detected as expected.
PS: The single-double-quoted string does the same with function return.

**Comment by Animeshz** [comment]
Ok it seems like, after `: String` return type there, equals is not highlighted. Indicating that single expression return type is not handled.

**Comment by TWiStErRob** [comment]
I was about to report a similar issue. We're on a self-hosted GitHub Enterprise, so I guess it didn't propagate there yet. Would it have been a duplicate then?

Looks good here:
```kotlin
private fun Exception.isNetworkError(): Boolean {
    val message = this.message ?: return false 
    return message.startsWith("""Unable to resolve host "api.host.net"""") ||
           message.startsWith("failed to connect to api.host.net")
}
```

This is what I see in our PR:
![image](https://user-images.githubusercontent.com/2906988/119997357-8d014580-bfc7-11eb-8304-2ead25486f45.png)

**Comment by Animeshz** [comment]
@TWiStErRob Which PR messed it? The upstream (master branch) grammar seems to work fine in the lightshow:

![image](https://user-images.githubusercontent.com/26714676/120068302-6f061480-c09d-11eb-837f-a13c17b0c04f.png)

**Comment by Animeshz** [comment]
Oh sorry I didn't read the comment fully, your issue is dup of #26 the triple quotation mark ends as soon as possible, so next (4th quote) was getting considered as beginning of new string. This is strange that it have been merged back in December yet is not updated in gh enterprise 🤔 I guess you could raise a ticket there to pull and apply the changes.

**Comment by TWiStErRob** [comment]
I'll double-check, maybe it's just my company's updates that lagging. Thanks for the confirm.
