### ISSUE TITLE
Small syntax highlight issue

### ISSUE THREAD

**Issue by EugeneOsipenko** [nishtahir/language-kotlin#7]
Noticed small issue with syntax highlight in this line - https://github.com/JakeWharton/RxBinding/blob/dad6bbd478bc1c34985fcf2a0f4dd408b2b2ad88/rxbinding/src/main/java/com/jakewharton/rxbinding3/view/ViewClickObservable.kt#L49

![2018-11-26 11 46 21](https://user-images.githubusercontent.com/5588852/49029906-899a6280-f1ae-11e8-84e1-0393a0419ed7.png)

"is" part of isDisposed is highlighted.

**Comment by nishtahir** [comment]
Should be fixed in the next linguist release.
