### ISSUE TITLE
Does not highlight methods correctly

### ISSUE THREAD

**Issue by Pato94** [nishtahir/language-kotlin#9]
As you can see in the following image, there's a little issue with the highlighting at the first method of this object
![image](https://user-images.githubusercontent.com/7254011/49161111-f3c61b00-f306-11e8-8969-bb22658e7096.png)

### Basic Example
```kotlin
val a = SomeClass(object : SomeInterface {
  override fun someMethod() {
    b = someExternalMethod()
    c.someCMethod(b)
  }

  override fun anotherMethod() {
  }
})
```

Digging a little deeper, I found out that if you remove the first line of `someMethod`, highlighting for the second method goes off too!
```kotlin
val a = SomeClass(object : SomeInterface {
  override fun someMethod() {
    c.someCMethod(b)
  }

  override fun anotherMethod() {
  }
})
```

So I'm not really sure about what's going on here, but this is valid kotlin and I think it should be correctly highlighted.

:wave:

**Comment by nishtahir** [comment]
Looks like this was fixed in #21.
